### ISSUE TITLE
How to connect multiple permissioned chains into single firefly-ethconnect instance

### ISSUE THREAD

**Issue by anujmax** [hyperledger/firefly-ethconnect#190]
Is it possible connect multiple permissioned chains into single firefly-ethconnect instance? if yes, how?

**Comment by peterbroadhurst** [comment]
Hi @anujmax, EthConnect is designed to be a microservice.
So I would recommend you run multiple instances of EthConnect, each against a single blockchain.

**Comment by peterbroadhurst** [comment]
In the FireFly Core orchestration layer that sits in front of EthConnect, the answer is a little more nuanced - and likely to evolve in the future. However, even as this evolves I'm confident the 1:1 architecture recommendation between an EthConnect microservice runtime, and a blockchain, will remain.
